### ISSUE TITLE
This is the error i get whenever i try running the bot, i changed the token and the owner id to mine and it is still not working

### ISSUE THREAD

**Issue by ForSomeCodezYT** [Makeliiii/Leninardo#1]
```
import LeninardoClient from './client/Leninardo'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by Makeliiii** [comment]
I'll assume you have installed all the dependencies and that babel configurations are the same as here. What commands are you running to start up the bot?

**Comment by Makeliiii** [comment]
Going to close this issue since it's been almost two weeks now. Guess I'm at fault for replying way late...
